
import React from 'react';
import Link from 'next/link';
import { fetchReportByFilename } from '../../../lib/api';
import { notFound } from 'next/navigation';

interface PageProps {
    params: Promise<{ id: string }>;
}

export default async function ReportDetailPage({ params }: PageProps) {
    const { id } = await params;
    const report = await fetchReportByFilename(id);

    if (!report) {
        notFound();
    }

    return (
        <main className="min-h-screen bg-[#050505] text-white selection:bg-blue-500/30 overflow-x-hidden">
            {/* Dynamic Background */}
            <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_50%_50%,rgba(17,24,39,1)_0%,rgba(5,5,5,1)_100%)]" />
            <div className="fixed inset-0 -z-10 opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />

            <header className="border-b border-white/5 bg-black/40 backdrop-blur-2xl sticky top-0 z-50">
                <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
                    <Link href="/" className="flex items-center gap-4 group">
                        <div className="h-10 w-10 rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-500 flex items-center justify-center font-black text-xl shadow-lg shadow-blue-500/40 transform group-hover:rotate-6 transition-transform">
                            A
                        </div>
                        <div className="hidden sm:block">
                            <h1 className="text-xl font-bold tracking-tight">Ayato Studio</h1>
                            <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em]">Back to Portal</p>
                        </div>
                    </Link>

                    <nav className="flex items-center gap-4">
                        <span className="px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-[10px] font-bold uppercase tracking-widest">
                            {report.category}
                        </span>
                        <div className="h-8 w-px bg-white/10 mx-2" />
                        <span className="text-sm text-gray-500 font-medium">
                            {new Date(report.timestamp).toLocaleDateString()}
                        </span>
                    </nav>
                </div>
            </header>

            <article className="mx-auto max-w-4xl px-6 py-24">
                {/* Hero Header */}
                <div className="mb-16">
                    <div className="flex items-center gap-3 text-blue-500 font-bold text-xs uppercase tracking-[0.3em] mb-6">
                        <div className="h-px w-12 bg-blue-500/50" />
                        Intelligence Report
                    </div>
                    <h2 className="text-5xl md:text-7xl font-black tracking-tighter mb-8 leading-[0.9]">
                        {report.title}
                    </h2>

                    <div className="flex flex-wrap items-center gap-6 p-6 rounded-3xl border border-white/5 bg-white/[0.02] backdrop-blur-xl">
                        <div className="flex items-center gap-3">
                            <div className="h-8 w-8 rounded-full bg-gray-800 flex items-center justify-center text-xs font-bold">AI</div>
                            <div>
                                <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Generated By</p>
                                <p className="text-sm font-bold">Ayato Intelligence Engine</p>
                            </div>
                        </div>
                        <div className="h-10 w-px bg-white/10" />
                        <div>
                            <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Market focus</p>
                            <p className="text-sm font-bold capitalize">{report.market}</p>
                        </div>
                        <div className="h-10 w-px bg-white/10" />
                        <div>
                            <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Reliability</p>
                            <p className="text-sm font-bold text-blue-400">Verified Artifact</p>
                        </div>
                    </div>
                </div>

                {/* Content */}
                <div className="relative group">
                    <div className="absolute -inset-4 bg-gradient-to-b from-blue-600/5 to-transparent rounded-[3rem] -z-10 blur-2xl" />

                    <div className="p-8 md:p-12 rounded-[2.5rem] border border-white/5 bg-black/40 backdrop-blur-3xl shadow-2xl">
                        <div className="prose prose-invert prose-blue max-w-none">
                            <div className="text-gray-300 leading-relaxed text-lg whitespace-pre-wrap font-medium space-y-6">
                                {report.content}
                            </div>
                        </div>
                    </div>
                </div>

                {/* CTA / Footer of Article */}
                <div className="mt-16 p-8 rounded-[2.5rem] border border-blue-500/20 bg-blue-500/5 flex flex-col items-center text-center">
                    <div className="h-16 w-16 rounded-3xl bg-blue-600/20 flex items-center justify-center text-blue-500 mb-6 font-black text-2xl">A</div>
                    <h4 className="text-2xl font-black mb-4">Want deeper insights?</h4>
                    <p className="text-gray-400 max-w-md mb-8">
                        Our intelligence engine processes thousands of data points daily.
                        Subscribe to our enterprise plan for real-time alerts and research tools.
                    </p>
                    <Link href="/logichive" className="rounded-full bg-blue-600 px-8 py-4 text-sm font-black text-white transition-all hover:bg-blue-500 hover:scale-105 active:scale-95 shadow-xl shadow-blue-600/20">
                        Get Started with LogicHive
                    </Link>
                </div>
            </article>

            <footer className="mt-24 border-t border-white/5 py-12 bg-black/40 backdrop-blur-xl">
                <div className="mx-auto max-w-7xl px-6 flex justify-between items-center text-gray-500 text-xs">
                    <p>© 2026 Ayato Studio. All rights reserved.</p>
                    <div className="flex gap-6">
                        <a href="#" className="hover:text-white">Privacy</a>
                        <a href="#" className="hover:text-white">Terms</a>
                        <Link href="/" className="hover:text-white">Back to Hub</Link>
                    </div>
                </div>
            </footer>
        </main>
    );
}

export async function generateStaticParams() {
    try {
        const reports = await fetchReports();
        return reports.map((report) => ({
            id: report.filename,
        }));
    } catch (error) {
        console.error('Failed to generate static params for reports:', error);
        return [];
    }
}
