import React from 'react';
import Link from 'next/link';
import Markdown from 'react-markdown';
import { cn } from "@/lib/utils";
import { Report } from '../lib/api';

interface ReportViewProps {
    report: Report;
}

export default function ReportView({ report }: ReportViewProps) {
    return (
        <main className="min-h-screen bg-[#050505] text-white selection:bg-blue-500/30 overflow-x-hidden">
            {/* Dynamic Background */}
            <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_50%_50%,rgba(17,24,39,1)_0%,rgba(5,5,5,1)_100%)]" />
            <div className="fixed inset-0 -z-10 opacity-20 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />

            <article className="mx-auto max-w-4xl px-6 py-12 md:py-24">
                {/* Hero Header */}
                <div className="mb-12">
                    <div className="flex items-center gap-3 text-blue-500 font-bold text-xs uppercase tracking-[0.3em] mb-6">
                        <div className="h-px w-12 bg-blue-500/50" />
                        Intelligence Report
                    </div>
                    <h2 className="text-4xl sm:text-5xl md:text-7xl font-black tracking-tighter mb-8 leading-[0.9]">
                        {report.title}
                    </h2>

                    <div className="grid grid-cols-2 lg:flex lg:flex-wrap items-center gap-4 md:gap-6 p-4 md:p-6 rounded-3xl border border-white/5 bg-white/[0.02] backdrop-blur-xl">
                        <div className="flex items-center gap-3 col-span-2 lg:col-span-1 mb-2 lg:mb-0">
                            <div className="h-8 w-8 rounded-full bg-gray-800 flex items-center justify-center text-xs font-bold">AI</div>
                            <div>
                                <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Generated By</p>
                                <p className="text-sm font-bold">Ayato Intelligence</p>
                            </div>
                        </div>
                        <div className="hidden lg:block h-10 w-px bg-white/10" />
                        <div>
                            <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Market</p>
                            <p className="text-sm font-bold capitalize">{report.market}</p>
                        </div>
                        <div className="lg:hidden h-full w-px bg-white/10 mx-auto" />
                        <div className="hidden lg:block h-10 w-px bg-white/10" />
                        <div>
                            <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Language</p>
                            <p className="text-sm font-bold">{report.language.toUpperCase()}</p>
                        </div>
                        {report.sourceUrl && (
                            <>
                                <div className="col-span-2 h-px lg:hidden bg-white/10 my-1" />
                                <div className="hidden lg:block h-10 w-px bg-white/10" />
                                <div className="col-span-2 lg:col-span-1">
                                    <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Source</p>
                                    <a
                                        href={report.sourceUrl}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="text-sm font-bold text-blue-400 hover:text-blue-300 transition-colors"
                                    >
                                        View Original →
                                    </a>
                                </div>
                            </>
                        )}
                    </div>
                </div>

                {/* Content with Markdown Rendering */}
                <div className="relative group">
                    <div className="absolute -inset-4 bg-gradient-to-b from-blue-600/5 to-transparent rounded-[3rem] -z-10 blur-2xl" />

                    <div className="p-5 md:p-12 rounded-3xl md:rounded-[2.5rem] border border-white/5 bg-black/40 backdrop-blur-3xl shadow-2xl">
                        <div className="
                            prose prose-invert prose-blue max-w-none
                            prose-headings:font-black prose-headings:tracking-tight
                            prose-h1:text-3xl md:prose-h1:text-4xl prose-h1:mb-8
                            prose-h2:text-2xl md:prose-h2:text-3xl prose-h2:mb-6 prose-h2:mt-12
                            prose-h3:text-xl md:prose-h3:text-2xl prose-h3:mb-4 prose-h3:mt-10
                            prose-h4:text-lg md:prose-h4:text-xl prose-h4:mb-3 prose-h4:mt-8 prose-h4:text-blue-400
                            prose-p:text-gray-300 prose-p:leading-relaxed prose-p:text-base md:prose-p:text-lg
                            prose-strong:text-white prose-strong:font-bold
                            prose-em:text-blue-300
                            prose-li:text-gray-300 prose-li:text-base md:prose-li:text-lg
                            prose-ul:space-y-2
                            prose-hr:border-white/10 prose-hr:my-12
                            prose-a:text-blue-400 prose-a:no-underline hover:prose-a:text-blue-300
                            prose-blockquote:border-l-4 prose-blockquote:border-blue-500/40 prose-blockquote:bg-blue-500/5 prose-blockquote:rounded-r-xl prose-blockquote:py-4 prose-blockquote:px-6 prose-blockquote:my-8
                        ">
                            <Markdown
                                components={{
                                    blockquote: ({ node, ...props }) => {
                                        const extractText = (nodes: any): string => {
                                            return React.Children.toArray(nodes)
                                                .map(child => {
                                                    if (typeof child === 'string') return child;
                                                    if (typeof child === 'number') return String(child);
                                                    if ((child as any)?.props?.children) return extractText((child as any).props.children);
                                                    return '';
                                                })
                                                .join('');
                                        };

                                        const content = extractText(props.children);
                                        const alertType = /\[!(IMPORTANT|NOTE)\]/i.exec(content);

                                        if (alertType) {
                                            const type = alertType[1].toUpperCase();
                                            const isImportant = type === "IMPORTANT";
                                            const cleanContent = content
                                                .replace(/^[>\s]*/, "")
                                                .replace(/\[!(IMPORTANT|NOTE)\]/i, "")
                                                .replace(/^[>\s]*/, "")
                                                .trim();

                                            return (
                                                <div className={cn(
                                                    "my-8 rounded-2xl border p-6 backdrop-blur-sm shadow-2xl",
                                                    isImportant ? "border-red-500/40 bg-red-500/10" : "border-blue-500/40 bg-blue-500/10"
                                                )}>
                                                    <div className={cn(
                                                        "flex items-center gap-2 font-black uppercase tracking-widest text-[10px] md:text-xs mb-4",
                                                        isImportant ? "text-red-400" : "text-blue-400"
                                                    )}>
                                                        {isImportant ? (
                                                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                                                        ) : (
                                                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
                                                        )}
                                                        {isImportant ? "Priority Notice" : "Information"}
                                                    </div>
                                                    <div className="text-gray-100 leading-relaxed italic font-medium text-sm md:text-base">
                                                        {cleanContent}
                                                    </div>
                                                </div>
                                            );
                                        }
                                        return <blockquote className="border-l-4 border-white/10 pl-6 my-6 italic text-gray-400 font-medium" {...props} />;
                                    },
                                    p: ({ node, ...props }) => {
                                        const extractText = (nodes: any): string => {
                                            return React.Children.toArray(nodes)
                                                .map(child => {
                                                    if (typeof child === 'string') return child;
                                                    if (typeof child === 'number') return String(child);
                                                    if ((child as any)?.props?.children) return extractText((child as any).props.children);
                                                    return '';
                                                })
                                                .join('');
                                        };

                                        const content = extractText(props.children);
                                        const alertType = /^[>\s]*\[!(IMPORTANT|NOTE)\]/i.exec(content);
                                        
                                        if (alertType) {
                                            const type = alertType[1].toUpperCase();
                                            const isImportant = type === "IMPORTANT";
                                            const cleanContent = content
                                                .replace(/^[>\s]*\[!(IMPORTANT|NOTE)\]/i, "")
                                                .replace(/^[>\s]*/, "")
                                                .trim();

                                            return (
                                                <div className={cn(
                                                    "my-8 rounded-2xl border p-6 backdrop-blur-sm shadow-2xl",
                                                    isImportant ? "border-red-500/40 bg-red-500/10" : "border-blue-500/40 bg-blue-500/10"
                                                )}>
                                                    <div className={cn(
                                                        "flex items-center gap-2 font-black uppercase tracking-widest text-[10px] md:text-xs mb-4",
                                                        isImportant ? "text-red-400" : "text-blue-400"
                                                    )}>
                                                        {isImportant ? (
                                                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
                                                        ) : (
                                                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
                                                        )}
                                                        {isImportant ? "Priority Notice" : "Information"}
                                                    </div>
                                                    <div className="text-gray-100 leading-relaxed italic font-medium text-sm md:text-base">
                                                        {cleanContent}
                                                    </div>
                                                </div>
                                            );
                                        }
                                        return <p className="mb-6 last:mb-0 leading-relaxed text-gray-300 font-medium" {...props} />;
                                    }
                                }}
                            >
                                {report.content}
                            </Markdown>
                        </div>
                    </div>
                </div>

                {/* CTA / Footer of Article */}
                <div className="mt-16 p-8 rounded-[2.5rem] border border-blue-500/20 bg-blue-500/5 flex flex-col items-center text-center">
                    <div className="h-16 w-16 rounded-3xl bg-blue-600/20 flex items-center justify-center text-blue-500 mb-6 font-black text-2xl">A</div>
                    <h4 className="text-2xl font-black mb-4">Want deeper insights?</h4>
                    <p className="text-gray-400 max-w-md mb-8">
                        Our intelligence engine processes thousands of data points daily.
                        Subscribe to our enterprise plan for real-time alerts and research tools.
                    </p>
                    <Link href="/logichive" className="rounded-full bg-blue-600 px-8 py-4 text-sm font-black text-white transition-all hover:bg-blue-500 hover:scale-105 active:scale-95 shadow-xl shadow-blue-600/20">
                        Get Started with LogicHive
                    </Link>
                </div>
            </article>
        </main>
    );
}
